# Generated by Django 5.1 on 2024-08-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_choice_user_poll_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
