# Generated by Django 5.1 on 2024-08-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_choice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='allowEditing',
            field=models.BooleanField(default=False),
        ),
    ]
